"""#8: is a row generated by intervals?  W_ij ~ f(pos_i - pos_j), with 768 input
positions, 768 output positions, and one shared curve f (a 4096-bin lookup),
all learned by gradient descent on one real 768x768 square. Compared to a
random control and to the best rank-4 fit."""
import torch, math
from transformers import GPT2LMHeadModel
torch.set_num_threads(4); torch.manual_seed(0)
def fit(W, steps=3000):
    d = W.shape[0]
    pi = torch.nn.Parameter(torch.rand(d) * 4096); po = torch.nn.Parameter(torch.rand(d) * 4096)
    f = torch.nn.Parameter(torch.zeros(4096)); g = torch.nn.Parameter(torch.ones(d))   # per-row gain (the lap counter)
    opt = torch.optim.Adam([pi, po, f, g], lr=3.0)
    for s in range(steps):
        iv = (pi[:, None] - po[None, :]) % 4096
        lo = iv.floor().long() % 4096; w = iv - iv.floor()
        Wf = g[:, None] * ((1 - w) * f[lo] + w * f[(lo + 1) % 4096])
        loss = ((Wf - W) ** 2).mean()
        opt.zero_grad(); loss.backward(); opt.step()
        if s == 1500:
            for pg in opt.param_groups: pg["lr"] = 0.5
    return float((Wf - W).norm() / W.norm())
m = GPT2LMHeadModel.from_pretrained("gpt2")
W = m.transformer.h[5].attn.c_proj.weight.detach().float()
U, S, V = torch.linalg.svd(W); W4 = (U[:, :4] * S[:4]) @ V[:4]
print(f"  h5 attn.c_proj: interval fit rel err {fit(W):.3f}   (rank-4 fit {float((W4 - W).norm() / W.norm()):.3f})", flush=True)
R = torch.randn(768, 768) / 27
print(f"  random control: interval fit rel err {fit(R):.3f}", flush=True)
